#!/bin/bash
bar-net() {
	state=""
	if [ -f /sys/class/net/e*/operstate ]; then
		eth=$(cat /sys/class/net/e*/operstate)
	fi

	if [ -f /sys/class/net/w*/operstate ]; then
		wifi=$(cat /sys/class/net/w*/operstate)
	fi

	if [ -f /sys/class/net/tun*/operstate ]; then
		tun=$(cat /sys/class/net/tun*/operstate)
	fi
	
	if [ "$eth" = "up" ]; then
		state=$state"󰈁"
	fi
	
	if [ "$wifi" = "up" ]; then
		state=$state"󰖩"
	fi
	
	if [ -n "$tun" ]; then
		state=$state""
	fi

	echo $state
}

command=$1

if [ "$command" = "net" ]; then
	bar-net 
elseif [ "$command" = "time" ]; then
	echo $(date +"%H:%M")
else
	echo "Invalid command"
fi