#!/bin/bash

source /usr/local/bin/asndenv

internalspeaker=$(pactl list short sinks | grep ${internalspeakerid} | awk '{print $2}')
internalmic=$(pactl list short sources | grep ${internalmicid} | awk '{print $2}')

focspeaker=$(pactl list short sinks | grep ${focspeakerid} | awk '{print $2}')
focmic=$(pactl list short sources | grep ${focmicid} | awk '{print $2}')

zvspeaker=$(pactl list short sinks | grep ${zvspeakerid} | awk '{print $2}')
zvmic=$(pactl list short sources | grep ${zvmicid} | awk '{print $2}')

h6speaker=$(pactl list short sinks | grep ${h6speakerid} | awk '{print $2}')
h6mic=$(pactl list short sources | grep ${h6micid} | awk '{print $2}')

dummyspeaker=$(pactl list short sinks | grep ${dummyspeakerid} | awk '{print $2}')
dummymic=$(pactl list short sources | grep ${dummymicid} | awk '{print $2}')

if [ -n "$focmic" ]
then
    echo "Focusrite is present"
    selected_output=$focspeaker
    selected_input=$focmic
    echo $selected_output $selected_input
elif [ -n "$zvmic" ]
then
    echo "Logitech is present"
    selected_output=$zvspeaker
    selected_input=$zvmic
    echo $selected_output $selected_output
elif [ -n "$h6mic" ]
then
    echo "H6 is present"
    selected_output=$h6speaker
    selected_input=$h6mic
    echo $selected_output $selected_output
elif [ -n "$internalmic" ]
then
    echo "Internal mic is present"
    selected_output=$internalspeaker
    selected_input=$internalmic
    echo $selected_output $selected_output
else
    echo "No sound device found choosing dummy devices"
    selected_output=$dummyspeaker
    selected_input=$dummymic
    echo $selected_output $selected_output
fi

speakers=$selected_output
mic=$selected_input

asnd $selected_output $selected_input
