#!/bin/bash

# comma separated list of sinks
speakers=$1

mic=$2

speakervolume=${3:-45}

micvolume=${4:-100}

if [ -z "$speakers" ]; then
    echo "No speakers selected. Exiting."
    exit 1
fi
if [ -z "$mic" ]; then
    echo "No mic selected. Exiting."
    exit 1
fi

# 
echo "hookup from-desktop to physical speakers"
cspeaker_module_id=$(pactl list short modules | grep "sink_name=from-desktop" | awk '{print $1}')
cspeaker_sink_input_id=$(pactl -f json list sink-inputs | jq -r ".[] | select(.owner_module == \"$cspeaker_module_id\") | .index")
pacmd move-sink-input $cspeaker_sink_input_id $speakers

echo "hookup from-desktop to physical speakers"
cspeaker_module_id=$(pactl list short modules | grep "sink_name=from-caller" | awk '{print $1}')
cspeaker_sink_input_id=$(pactl -f json list sink-inputs | jq -r ".[] | select(.owner_module == \"$cspeaker_module_id\") | .index")
pacmd move-sink-input $cspeaker_sink_input_id $speakers

# echo "hookup mics_raw to physical mic"
# mics_raw_module_id=$(pactl list short modules | grep "source_name=mics-raw" | awk '{print $1}')
# mics_raw_source_output_id=$(pactl -f json list source-outputs | jq -r ".[] | select(.owner_module == \"$mics_raw_module_id\") | .index")
# pacmd move-source-output $mics_raw_source_output_id $mic

echo "hookup mic01 to physical mic"
mic01_module_id=$(pactl list short modules | grep "source_name=mic01-processed" | awk '{print $1}')
mic01_source_output_id=$(pactl -f json list source-outputs | jq -r ".[] | select(.owner_module == \"$mic01_module_id\") | .index")
pacmd move-source-output $mic01_source_output_id $mic

echo "hookup mic02 to physical mic"
mic02_module_id=$(pactl list short modules | grep "source_name=mic02-processed" | awk '{print $1}')
mic02_source_output_id=$(pactl -f json list source-outputs | jq -r ".[] | select(.owner_module == \"$mic02_module_id\") | .index")
pacmd move-source-output $mic02_source_output_id $mic

# set default mic apps
pactl set-default-source mic01-processed

# set default output for apps
pactl set-default-sink from-desktop

# set physical volumes
pactl set-sink-volume $speakers ${speakervolume}%
pactl set-sink-mute $speakers 0

pactl set-source-volume $mic ${micvolume}%
pactl set-source-mute $mic 0

# set vitual volumes
pactl set-sink-volume from-desktop 95%
pactl set-sink-mute from-desktop 0

pactl set-sink-volume from-caller 95%
pactl set-sink-mute from-caller 0

pactl set-sink-volume to-caller-sink 100%
pactl set-sink-mute to-caller-sink 0

# pactl set-sink-volume cspeakers 45%
# pactl set-sink-mute cspeakers 0

pactl set-source-volume to-caller 100%
pactl set-source-mute to-caller 0

# pactl set-source-volume mics-raw 100%
# pactl set-source-mute mics-raw 0

pactl set-source-volume mic01-processed 100%
pactl set-source-mute mic01-processed 0

pactl set-source-volume mic02-processed 100%
pactl set-source-mute mic02-processed 0

kill -44 $(pidof dwmblocks)
