#!/bin/bash

# script for pipewire connection

# comma separated list of sinks
speakers=$1

mic=$2


echo "hookup cspeaker to physical speakers"
channels=$(pw-link -i | grep $speakers | grep -E "FL|FR" | wc -l)
if [ $channels -eq 2 ]; then
id=$(pw-link -lI | grep "|->.*$speakers.*FL" | awk '{print $1}')
pw-link -d $id
pw-link cspeakers:monitor_FL ${speakers}:playback_FL

id=$(pw-link -lI | grep "|->.*$speakers.*FR" | awk '{print $1}')
pw-link -d $id
pw-link cspeakers:monitor_FR ${speakers}:playback_FR
fi

echo "hookup from-desktop to cspeakers and to-caller-sink"
pw-link from-desktop:monitor_FL cspeakers:playback_FL
pw-link from-desktop:monitor_FR cspeakers:playback_FR
pw-link from-caller:monitor_FL cspeakers:playback_FL
pw-link from-caller:monitor_FR cspeakers:playback_FR
pw-link from-desktop:monitor_FL to-caller-sink:playback_FL
pw-link from-desktop:monitor_FR to-caller-sink:playback_FR

echo "hookup mics_raw to physical mic"
channels=$(pw-link -o | grep $mic | grep -E "FL|FR" | wc -l)
if [ $channels -eq 2 ]; then
id=$(pw-link -lI | grep "|<-.*$mic.*FL" | awk '{print $1}')
pw-link -d $id
pw-link ${mic}:capture_FL mic01-processed:input_MONO
pw-link mic01-processed:capture_MONO to-caller-sink:playback_FL
pw-link mic01-processed:capture_MONO to-caller-sink:playback_FR


id=$(pw-link -lI | grep "|<-.*$mic.*FR" | awk '{print $1}')
pw-link -d $id
pw-link ${mic}:capture_FR mic02-processed:input_MONO
pw-link mic02-processed:capture_MONO to-caller-sink:playback_FL
pw-link mic02-processed:capture_MONO to-caller-sink:playback_FR
fi

if [ $channels -eq 1 ]; then
id=$(pw-link -lI | grep "|<-.*$mic.*MONO" | awk '{print $1}')
pw-link -d $id
pw-link ${mic}:capture_MONO mic01-processed:input_MONO
fi

echo "hookup mic01 to physical mic"

echo "hookup mic02 to physical mic"

# set default mic apps
pactl set-default-source mic01-processed

# set default output for apps
pactl set-default-sink from-desktop

# set physical volumes
pactl set-sink-volume $speakers 100%
pactl set-sink-mute $speakers 0

pactl set-source-volume $mic 100%
pactl set-source-mute $mic 0

# set vitual volumes
pactl set-sink-volume from-desktop 95%
pactl set-sink-mute from-desktop 0

pactl set-sink-volume from-caller 95%
pactl set-sink-mute from-caller 0

pactl set-sink-volume to-caller-sink 100%
pactl set-sink-mute to-caller-sink 0

pactl set-sink-volume cspeakers 45%
pactl set-sink-mute cspeakers 0

pactl set-source-volume to-caller 100%
pactl set-source-mute to-caller 0

pactl set-source-volume mics-raw 100%
pactl set-source-mute mics-raw 0

pactl set-source-volume mic01-processed 100%
pactl set-source-mute mic01-processed 0

pactl set-source-volume mic02-processed 100%
pactl set-source-mute mic02-processed 0

kill -44 $(pidof dwmblocks)
