#!/bin/bash
usbmic=$(pactl list short sources | grep alsa_input.usb-Focusrite_Scarlett_2i2_USB_Y8QWAQ69B26B58-00.analog-stereo | awk '{print $2}')
usbspeaker=$(pactl list short sinks | grep alsa_output.usb-Focusrite_Scarlett_2i2_USB_Y8QWAQ69B26B58-00.analog-stereo | awk '{print $2}')

internalmic=$(pactl list short sources | grep alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source | awk '{print $2}')
internalspeaker=$(pactl list short sinks | grep alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink | awk '{print $2}')

if [ -n "$usbmic" ]
then
    echo "Focusrite is present"
    selected_output=$usbspeaker
    selected_input=$usbmic
    echo $selected_output $selected_output
    confsnd $selected_output $selected_input
else
    echo "No external sound choosing internal devices"
    selected_output=$internalspeaker
    selected_input=$internalmic
    echo $selected_output $selected_output
    confsnd $selected_output $selected_output
fi

