#!/bin/bash
source /usr/local/bin/asndenv

csndint

CARD=$(pactl list short cards | grep bluez_card | awk '{print $2}')
pactl set-card-profile "$CARD" a2dp_sink

speakers=$bthspeakerid
mic=$bthmicid
speakervolume=$bthspeakervolume
micvolume=$bthmicvolume

asnd $speakers $mic $speakervolume $micvolume
