#!/bin/bash

# Take one argument from the commandline: VM name
if ! [ $# -eq 1 ]; then
    echo "Usage: $0 <node-name>"
    exit 1
fi

VMS_DIR=/home/${USER}/virt/runtime
virsh destroy $1
virsh undefine $1
rm -f $VMS_DIR/$1.qcow2
rm -f $VMS_DIR/$1-data.qcow2
rm -f $VMS_DIR/$1-cidata.iso
echo "$(date -R) Removing ip from dhcp server..."
virsh net-update default delete ip-dhcp-host "<host name='$1' />" --live --config
ansible 127.0.0.1 -m lineinfile -a "path=$VMS_DIR/vms regexp='^.*address=/$1.*$' state=absent"
nmcli general reload
