#!/bin/bash
kubectl apply -n otel-demo -f  https://raw.githubusercontent.com/alainpham/debian-os-image/master/scripts/k8s/oteldemo/oteldemo.yaml
 


wget -O /tmp/expose.yaml https://raw.githubusercontent.com/alainpham/debian-os-image/master/scripts/k8s/oteldemo/expose.yaml
envsubst < /tmp/expose.yaml | kubectl apply -n otel-demo -f -

