#!/bin/bash



kubectl apply -n otel-demo -f  https://raw.githubusercontent.com/alainpham/debian-os-image/master/scripts/k8s/oteldemo/oteldemo.yaml
kubectl apply -n otel-demo -f  https://raw.githubusercontent.com/alainpham/debian-os-image/master/scripts/k8s/oteldemo/expose.yaml
