#!/bin/bash

curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_ENABLE="true" INSTALL_K3S_SKIP_START="true" INSTALL_K3S_VERSION="${K3S_VERSION}" K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --disable=servicelb,traefik --bind-address 172.17.0.1 --node-ip 172.17.0.1 --advertise-address 172.17.0.1" sh -

if command -v systemctl &> /dev/null; then
  sudo systemctl enable k3s
  sudo systemctl start k3s
else
  echo "Warning: systemd is not available. Please start k3s manually."
fi

if command -v openrc-run &> /dev/null || command -v openrc &> /dev/null; then
  sudo rc-update add k3s default
  sudo service k3s start
fi

mkdir -p $HOME/.kube ; cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config