#!/bin/bash

setxkbmap fr

numlockx &

while true; do
    bgfile=$(ls /usr/share/backgrounds/ | shuf -n 1)
    feh --bg-scale /usr/share/backgrounds/${bgfile} &
    # Log stderror to a file
    dwm 2> ~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
